environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%PYTHON%\\python.exe -m pip install -v -U pip setuptools"
  - "%PYTHON%\\python.exe -m pip install -v -e ."
  - "%PYTHON%\\python.exe -m pip install unittest2 nose2 codecov coverage"
build: off
test_script:
  - "%PYTHON%\\python.exe -m nose2 -v --log-capture --with-coverage src"
on_success:
  - "%PYTHON%\\Scripts\\codecov.exe"
