# travis CI config
language: python
matrix:
  include:
  - python: 2.7
    env: JYTHON=true
  - python: 2.7
    env: JYTHON=false
  - python: 3.3
    env: JYTHON=false
  - python: 3.4
    env: JYTHON=false
  - python: 3.5
    env: JYTHON=false
  - python: pypy
    env: JYTHON=false
cache: false
before_install:
  - sudo apt-get update -q
  - sudo apt-get install graphviz -y
  - if [ "$JYTHON" == "true" ]; then sudo apt-get install jython; fi
  - if [ "$JYTHON" == "true" ]; then export PYTHON_EXE=jython; jython -c "print ''"; else export PYTHON_EXE=python; fi
install:
  - $PYTHON_EXE -m pip install -v -U pip setuptools
  - $PYTHON_EXE -m pip install -v -e .
  - $PYTHON_EXE -m pip install -U unittest2 nose2 cov-core codecov coverage
script: $PYTHON_EXE -m nose2 -v --log-capture --with-coverage --coverage src --coverage examples -s src
after_success:
  - $PYTHON_EXE -m codecov
branches:
  only:
    - master
