# travis CI config
language: python
matrix:
  include:
#  - python: 2.7
#    env: JYTHON=org.python:jython-installer:2.7.1
  - python: 2.7
  - python: 3.3
  - python: 3.4
  - python: 3.5
  - python: pypy
cache: false
before_install:
  - sudo apt-get update -q
  - sudo apt-get install graphviz -y
  - python -m pip install -v -U pip setuptools virtualenv wheel
  - if [ -n "$JYTHON" ]; then bash ./.travis_before_install_jython.sh; source $HOME/myvirtualenv/bin/activate ;fi
  - if [ -n "$JYTHON" ]; then pip install jip; fi
  - if [ -n "$JYTHON" ]; then export CLASSPATH=$VIRTUAL_ENV/javalib/*; fi
install:
  - python -m pip install -v -e .
  - python -m pip install -U unittest2 nose2 cov-core codecov coverage
script: python -m nose2 -v --log-capture --with-coverage --coverage src --coverage examples -s src
after_success:
  - python -m codecov
branches:
  only:
    - master
