# travis CI config
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
cache: false
install:
  - pip install -e .
  - pip install codecov coverage
script: nosetests --with-coverage
after_success:
  - codecov
branches:
  only:
    - master
