# travis CI config
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
os:
 - linux
# - osx
cache: false
before_install:
  - sudo apt-get update -q
  - sudo apt-get install graphviz -y
install:
  - pip install -v -U pip setuptools
  - pip install -v -e .
  - pip install -U unittest2 nose2 cov-core codecov coverage
script: nose2 -v --log-capture --with-coverage
after_success:
  - codecov
branches:
  only:
    - master
