# travis CI config
language: python
matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7
    dist: xenial
  - python: pypy
  - python: pypy3
cache: false
before_install:
  - sudo apt-get update -q
  - sudo apt-get install graphviz -y
  - python -m pip install -v -U pip setuptools virtualenv wheel
install:
  - python -m pip install -v -e .
  - python -m pip install -U unittest2 nose2 cov-core codecov coverage
script: python -m nose2 -v --log-capture --with-coverage --coverage src --coverage examples -s src
after_success:
  - codecov
branches:
  only:
    - master
